/* Boxen */
ko_test(boxen,schwimmen,1).
ko_test(boxen,einzelsport,1).
ko_test(boxen,partnersport,1).
ko_test(boxen,teamsport,1).
ko_test(boxen,ballsport,1).
ko_test(boxen,sommersport,1).
ko_test(boxen,wintersport,2).
ko_test(boxen,outdoor,1).
ko_test(boxen,indoor,2).
ko_test(boxen,zuhause,1).
verf_test(boxen,familientauglichkeit,1).
verf_test(boxen,verletzungsrisiko,4).
verf_test(boxen,zeitfaktor,4).
verf_test(boxen,wettkampfbereitschaft,4).
verf_test(boxen,sozialer_aspekt,4).
verf_test(boxen,finanzieller_aspekt_einmalig,2).
verf_test(boxen,finanzieller_aspekt_laufend,2).
verf_test(boxen,kraft,4).
verf_test(boxen,ausdauer,4).
verf_test(boxen,koordination,4).
verf_test(boxen,praezision,4).

/* Frauensport */
ko_test(frau,schwimmen,1).
ko_test(frau,einzelsport,2).
ko_test(frau,partnersport,2).
ko_test(frau,teamsport,2).
ko_test(frau,ballsport,2).
ko_test(frau,sommersport,2).
ko_test(frau,wintersport,2).
ko_test(frau,outdoor,2).
ko_test(frau,indoor,2).
ko_test(frau,zuhause,1).
verf_test(frau,familientauglichkeit,1).
verf_test(frau,verletzungsrisiko,1).
verf_test(frau,zeitfaktor,1).
verf_test(frau,wettkampfbereitschaft,1).
verf_test(frau,sozialer_aspekt,1).
verf_test(frau,finanzieller_aspekt_einmalig,1).
verf_test(frau,finanzieller_aspekt_laufend,1).
verf_test(frau,kraft,1).
verf_test(frau,ausdauer,1).
verf_test(frau,koordination,1).
verf_test(frau,praezision,1).

/* Aerobic, Yoga, Leichtathletik */
ko_test(rieckeheer,schwimmen,2).
ko_test(rieckeheer,einzelsport,2).
ko_test(rieckeheer,partnersport,2).
ko_test(rieckeheer,teamsport,1).
ko_test(rieckeheer,ballsport,1).
ko_test(rieckeheer,sommersport,2).
ko_test(rieckeheer,wintersport,2).
ko_test(rieckeheer,outdoor,2).
ko_test(rieckeheer,indoor,2).
ko_test(rieckeheer,zuhause,1).
verf_test(rieckeheer,familientauglichkeit,1).
verf_test(rieckeheer,verletzungsrisiko,1).
verf_test(rieckeheer,zeitfaktor,2).
verf_test(rieckeheer,wettkampfbereitschaft,4).
verf_test(rieckeheer,sozialer_aspekt,2).
verf_test(rieckeheer,finanzieller_aspekt_einmalig,1).
verf_test(rieckeheer,finanzieller_aspekt_laufend,2).
verf_test(rieckeheer,kraft,2).
verf_test(rieckeheer,ausdauer,3).
verf_test(rieckeheer,koordination,3).
verf_test(rieckeheer,praezision,1).

ko_test(tom,schwimmen,2).
ko_test(tom,einzelsport,2).
ko_test(tom,partnersport,2).
ko_test(tom,teamsport,1).
ko_test(tom,ballsport,1).
ko_test(tom,sommersport,2).
ko_test(tom,wintersport,2).
ko_test(tom,outdoor,2).
ko_test(tom,indoor,2).
ko_test(tom,zuhause,1).
verf_test(tom,familientauglichkeit,1).
verf_test(tom,verletzungsrisiko,2).
verf_test(tom,zeitfaktor,3).
verf_test(tom,wettkampfbereitschaft,2).
verf_test(tom,sozialer_aspekt,2).
verf_test(tom,finanzieller_aspekt_einmalig,3).
verf_test(tom,finanzieller_aspekt_laufend,3).
verf_test(tom,kraft,3).
verf_test(tom,ausdauer,2).
verf_test(tom,koordination,3).
verf_test(tom,praezision,3).

ko_test(fussball,schwimmen,1).
ko_test(fussball,einzelsport,1).
ko_test(fussball,partnersport,2).
ko_test(fussball,teamsport,2).
ko_test(fussball,ballsport,2).
ko_test(fussball,sommersport,2).
ko_test(fussball,wintersport,1).
ko_test(fussball,outdoor,2).
ko_test(fussball,indoor,1).
ko_test(fussball,zuhause,1).
verf_test(fussball,ausdauer,3).
verf_test(fussball,kraft,2).
verf_test(fussball,verletzungsrisiko,3).
verf_test(fussball,zeitfaktor,4).
verf_test(fussball,koordination,3).
verf_test(fussball,finanzieller_aspekt_einmalig,2).
verf_test(fussball,finanzieller_aspekt_laufend,2).
verf_test(fussball,familientauglichkeit,1).
verf_test(fussball,sozialer_aspekt,4).
verf_test(fussball,praezision,3).
verf_test(fussball,wettkampfbereitschaft,3).
