/* Boxen, Taekwondo/Aikido, Judo/Ju-Jutsu/Karate */
ko_test(boxen,schwimmen,1).
ko_test(boxen,einzelsport,1).
ko_test(boxen,partnersport,1).
ko_test(boxen,teamsport,2).
ko_test(boxen,ballsport,1).
ko_test(boxen,sommersport,1).
ko_test(boxen,wintersport,2).
ko_test(boxen,outdoor,2).
ko_test(boxen,indoor,2).
ko_test(boxen,zuhause,1).
verf_test(boxen,familientauglichkeit,1).
verf_test(boxen,verletzungsrisiko,2).
verf_test(boxen,zeitfaktor,3).
verf_test(boxen,wettkampfbereitschaft,4).
verf_test(boxen,sozialer_aspekt,1).
verf_test(boxen,finanzieller_aspekt_einmalig,2).
verf_test(boxen,finanzieller_aspekt_laufend,3).
verf_test(boxen,kraft,4).
verf_test(boxen,ausdauer,1).
verf_test(boxen,koordination,2).
verf_test(boxen,praezision,3).

/* Frauensport */
ko_test(frau,schwimmen,1).
ko_test(frau,einzelsport,2).
ko_test(frau,partnersport,2).
ko_test(frau,teamsport,2).
ko_test(frau,ballsport,2).
ko_test(frau,sommersport,2).
ko_test(frau,wintersport,2).
ko_test(frau,outdoor,2).
ko_test(frau,indoor,2).
ko_test(frau,zuhause,1).
verf_test(frau,familientauglichkeit,1).
verf_test(frau,verletzungsrisiko,1).
verf_test(frau,zeitfaktor,1).
verf_test(frau,wettkampfbereitschaft,1).
verf_test(frau,sozialer_aspekt,1).
verf_test(frau,finanzieller_aspekt_einmalig,1).
verf_test(frau,finanzieller_aspekt_laufend,1).
verf_test(frau,kraft,1).
verf_test(frau,ausdauer,1).
verf_test(frau,koordination,1).
verf_test(frau,praezision,1).
